# -*- coding: utf-8 -*-
"""PotholeDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEeiZgCZhhpBtH4q1Ls2CvHUSVqbofqB
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/pothole_dataset.zip -d /content/

!pip install ultralytics

from ultralytics import YOLO

!ls /content/

!cat /content/data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/data.yaml
# path: /content
# train: train/images
# val: valid/images
# test: test/images
# 
# names:
#   0: pothole

!ls /content/train/images | head
!ls /content/train/labels | head

# from ultralytics import YOLO

# model = YOLO("yolov8n.pt")

# model.train(
#     data="/content/data.yaml",
#     epochs=50,
#     imgsz=640,
#     batch=16
# )

# model.train(
#     data="/content/data.yaml",
#     epochs=50,
#     imgsz=640,
#     batch=16,
#     project="/content/drive/MyDrive/pothole_yolo",
#     name="train1",
#     exist_ok=True
# )

from ultralytics import YOLO

MODEL_PATH = "/content/drive/MyDrive/pothole_yolo/train1/weights/last.pt"

import os

if os.path.exists(MODEL_PATH):
    print("Resuming previous training...")
    model = YOLO(MODEL_PATH)
    model.train(resume=True)
else:
    print("Starting fresh training...")
    model = YOLO("yolov8n.pt")
    model.train(
        data="/content/data.yaml",
        epochs=100,
        imgsz=640,
        batch=16,
        project="/content/drive/MyDrive/pothole_yolo",
        name="train1",
        exist_ok=True
    )

BEST_MODEL = "/content/drive/MyDrive/pothole_yolo/train1/weights/best.pt"

model = YOLO(BEST_MODEL)

metrics=model.val(data='/content/data.yaml')
print(metrics)

model.predict(source="/content/test/images", conf=0.25, save=True)

model.val(data="/content/data.yaml", plots=True)

print("Precision:", metrics.results_dict['metrics/precision(B)'])
print("Recall:", metrics.results_dict['metrics/recall(B)'])
print("mAP50:", metrics.results_dict['metrics/mAP50(B)'])
print("mAP50-95:", metrics.results_dict['metrics/mAP50-95(B)'])

